

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app-network

  backend:
    image: nguyendai/mern-backend:${IMAGE_TAG:-latest}
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: always
    networks:
      - app-network

  frontend:
    image: nguyendai/mern-frontend:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    restart: always
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    ports:
      - "9100:9100"
    restart: always
    networks:
      - app-network
  
  mongo-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    command:
      - "--mongodb.uri=mongodb://mongo:27017"
      - "--collect-all"
      - "--compatible-mode"
    ports:
      - "9216:9216"
    restart: always
    networks:
      - app-network
    depends_on:
      - mongo
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge