- name: Deploy MERN DevOps App
  hosts: vps
  become: yes
  vars_files:
    - vars.yml

  tasks:

    # 🔄 Update hệ thống
    - name: Update apt
      apt:
        update_cache: yes

    # 🐳 Cài Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    # 📦 Cài docker-compose
    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present

    # 👤 Add user ubuntu vào docker group
    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # 📁 Clone project
    - name: Clone repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        force: yes

    - name: Ensure backend .env exists
      copy:
        dest: "{{ app_dir }}/backend/.env"
        content: |
          NODE_ENV=production
          PORT=5000
          MONGO_URI=mongodb://mongo:27017/todo
          JWT_SECRET=BI_MAT

    # 🚀 Run docker-compose
    - name: Deploy stack
      community.docker.docker_compose:
        project_src: "{{ app_dir }}"
        pull: yes
        state: present
